[package]
name = "watch-stl"
version = "0.1.2"
authors = ["Andrew Dirksen <andrew@dirksen.com>"]
edition = "2018"

[dependencies]
stl_io = "0.7.0"
kiss3d = "0.35.0"
notify = "5.1.0"
anyhow = "1.0.69"
