[package]
name = "watch-stl"
version = "0.1.2"
authors = ["Andrew Dirksen <andrew@dirksen.com>"]
edition = "2018"

[dependencies]
stl_io = "0.4.2"
kiss3d = "0.22.1"
nalgebra = "0.19.0"
notify = "4.0.14"
